//
//  CoreAVRPackageSupport.swift
//  SwiftAVRGenerator
//
//  Created by Friso De Backer on 10/04/2026.
//

import Foundation

struct CoreAVRPackageSupportFile {
    let relativePath: String
    let content: String

    var fileName: String {
        String(relativePath.split(separator: "/").last ?? "")
    }
}

enum CoreAVRPackageSupport {
    static func files(for core: GeneratedAVRCore, documentationDirectory: URL) -> [CoreAVRPackageSupportFile] {
        let generatedSourcePaths = generatedSourcePaths(for: core.files)

        return staticSupportFiles(documentationDirectory: documentationDirectory) + [
            CoreAVRPackageSupportFile(relativePath: "README.md", content: readme(for: core, generatedSourcePaths: generatedSourcePaths)),
            CoreAVRPackageSupportFile(relativePath: "board.include", content: boardInclude(for: core.device)),
            CoreAVRPackageSupportFile(relativePath: "CoreAVR.swift4p", content: swift4p(generatedSourcePaths: generatedSourcePaths))
        ]
    }

    private static let staticSupportTemplates = [
        ("Package.swift.template", "Package.swift"),
        ("module.modulemap", "module.modulemap"),
        ("CoreAVR.h", "CoreAVR.h"),
        ("Sources/CoreAVR/CoreAVR.swift", "Sources/CoreAVR/CoreAVR.swift"),
        ("Sources/CoreAVR/DigitalValue.swift", "Sources/CoreAVR/DigitalValue.swift"),
        ("Sources/CoreAVR/Utilities.swift", "Sources/CoreAVR/Utilities.swift")
    ]

    private static func staticSupportFiles(documentationDirectory: URL) -> [CoreAVRPackageSupportFile] {
        staticSupportTemplates.map { templatePath, outputPath in
            CoreAVRPackageSupportFile(
                relativePath: outputPath,
                content: staticSupportFile(
                    templatePath: templatePath,
                    outputPath: outputPath,
                    documentationDirectory: documentationDirectory
                )
            )
        }
    }

    private static func staticSupportFile(templatePath: String, outputPath: String, documentationDirectory: URL) -> String {
        let templateURL = documentationDirectory
            .appendingPathComponent("coreavr-package", isDirectory: true)
            .appendingPathComponent(templatePath, isDirectory: false)

        do {
            let contents = try String(contentsOf: templateURL, encoding: .utf8)

            guard outputPath.hasSuffix(".swift") else {
                return contents
            }

            let fileName = URL(fileURLWithPath: outputPath).deletingPathExtension().lastPathComponent
            return buildFileHeader(for: fileName, generateTypealias: false) + contents
        } catch {
            fatalError("Missing CoreAVR package template at \(templateURL.path): \(error)")
        }
    }

    private static func generatedSourcePaths(for files: [GeneratedCodeFile]) -> [String] {
        files
            .map { file in
                "Sources/CoreAVR/\(file.subdirectory)/\(file.fileName)"
            }
            .sorted()
    }

    private static func readme(for core: GeneratedAVRCore, generatedSourcePaths: [String]) -> String {
        let modules = availableModules(from: core.files)
        let moduleList = modules.isEmpty ? "- None" : modules.map { "- \($0)" }.joined(separator: "\n")
        let fileList = generatedSourcePaths.isEmpty ? "- None" : generatedSourcePaths.map { "- `\($0)`" }.joined(separator: "\n")

        return """
        # CoreAVR for \(core.name)

        Generated by HALGEN from `\(core.atdfFileName)`.

        ## Generated modules

        \(moduleList)

        ## Generated files

        \(fileList)
        """
    }

    private static func availableModules(from files: [GeneratedCodeFile]) -> [String] {
        var modules: [String] = []

        if files.contains(where: { $0.fileName == "AnalogToDigitalConverter.swift" }) {
            modules.append("AnalogToDigitalConverter")
        }
        if files.contains(where: { $0.fileName == "GPIO.swift" }) {
            modules.append("GPIO")
        }
        if files.contains(where: { $0.subdirectory == "module/Timer" }) {
            modules.append("Timer")
        }
        if files.contains(where: { $0.subdirectory == "module/UART" }) {
            modules.append("UART")
        }

        return modules.sorted()
    }

    private static func boardInclude(for device: AVRToolsDeviceFile) -> String {
        let chipName = device.devices.device.name
        let flashSize = device.memorySegmentSize(named: "FLASH", type: "flash") ?? 0
        let ramSize = device.memorySegmentSize(named: "IRAM", type: "ram") ?? 0

        return """
        RAM_SIZE=\(ramSize)
        FLASH_SIZE=\(flashSize)
        BAUD=115200
        CPU_FREQUENCY=16000000
        PROGRAMMER=arduino
        MCUMACRO=__AVR_\(chipName)__
        ARCH=\(device.devices.device.architecture.hasPrefix("AVR") ? "AVR" : device.devices.device.architecture)
        MCU=\(chipName.lowercased())
        CORE=\(estimatedCore(for: device))
        """
    }

    private static func estimatedCore(for device: AVRToolsDeviceFile) -> String {
        let name = device.devices.device.name.lowercased()
        let flashSize = device.memorySegmentSize(named: "FLASH", type: "flash") ?? 0

        if name.hasPrefix("atmega") {
            if flashSize > 0x20000 {
                return "avr6"
            }
            if flashSize > 0x10000 {
                return "avr51"
            }
            if flashSize <= 0x2000 {
                return "avr4"
            }
            return "avr5"
        }

        if name.hasPrefix("attiny") {
            if device.deviceParameter(named: "CORE_VERSION") == "AVR8L_0" {
                return "avrtiny"
            }
            return "avr25"
        }

        return "avr5"
    }

    private static func swift4p(generatedSourcePaths: [String]) -> String {
        let paths = [
            "module.modulemap",
            "Package.swift",
            "CoreAVR.h",
            "Sources/CoreAVR/DigitalValue.swift",
            "Sources/CoreAVR/CoreAVR.swift",
            "Sources/CoreAVR/Utilities.swift"
        ] + generatedSourcePaths

        let fileLines = paths.map { "- \($0)" }.joined(separator: "\n")

        return """
        files:
        \(fileLines)
        settings:
          BUILD_DIR: build
          INCLUDE_PRINTF_FLT: 'no'
        """
    }
}

private extension AVRToolsDeviceFile {
    func memorySegmentSize(named segmentName: String, type segmentType: String) -> Int? {
        for addressSpace in devices.device.addressSpaces.addressSpace {
            for segment in addressSpace.memorySegment {
                if segment.name == segmentName || segment.type == segmentType {
                    return integerValue(from: segment.size)
                }
            }
        }

        return nil
    }

    func deviceParameter(named parameterName: String) -> String? {
        guard devices.device.parameters?.param.name == parameterName else {
            return nil
        }

        return devices.device.parameters?.param.value
    }
}

private func integerValue(from string: String) -> Int? {
    let trimmedString = string.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()

    if trimmedString.hasPrefix("0x") {
        return Int(trimmedString.dropFirst(2), radix: 16)
    }

    return Int(trimmedString)
}
